firstweb/firstweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('pos/', include('pos.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstweb/myapp/urls.py
from django.urls import path
#from .views import Home, Sawatdee, AboutUs, Contact, TrackingPage, Ask
from .views import *



urlpatterns = [
    path('sawatdee', Sawatdee),
    path('', Home, name='home'), # name ข้างหลังคือไว้ใส่ใน {% url 'home' %}
    path('aboutus', AboutUs, name='about-us'), #www.bankshop.com/aboutus
    path('contact', Contact, name='contact'), #www.bankshop.com/contact
    path('tracking', TrackingPage, name='tracking'),
    path('ask', Ask, name='ask'),
    path('questions', Questions, name='questions'),
    path('answer/<int:askid>', Answer , name='answer'),
    path('blogs', Posts , name='post'),
    path('blog/<slug:slug>/', PostDetail , name='post-detail'),
    #Register and Login
    path('register', Register , name='register'),
    path('login', Login , name='login'),
    #products
    path('products', AllProduct , name='all-product'),
    path('discount', DiscountPage , name='discount'),
    path('product/<slug:slug>', ProductDetail , name='product-detail'),
    path('tracking-order/<str:tid>', TrackingOrderId, name= 'tracking-order-id-page'),
    # EP17 Cart
    path('add-cart/<str:pid>', AddToCart, name='add-to-cart'),
    path('cart/', MyCart , name='my-cart'),
    # End EP17
    # EP18
    path('edit-cart/', MyCartEdit , name='my-cart-edit'),
    path('checkout/', Checkout , name='checkout'),
    # End EP18
    # EP19
    path('orders/', CartOrderProduct , name='cart-order-product'),
    path('upload-slip/<str:order_id>/', UploadSlipOrder , name='upload-slip-order'),
    path('customer-all-order/', CustomerAllOrder , name='customer-all-order'),  
    path('update-status/<str:order_id>/<str:status>/', UpdatePaid , name='update-status'),  
    path('update-tracking/<str:order_id>/', CartOrderUpdateTracking , name='cart-order-update-tracking'),      
    path('my-order/<str:order_id>/', MyOrder , name='my-order'),      
    # End EP19
    # EP20 Rental 1
    path('machines/', AllMachine , name='all-machines-page'), 
    path('machine/<int:machine_id>/', MachineDetail , name='machine-detail-page'),          
    # End EP20
    # EP21 Rental 2
    path('machine/<int:machine_id>/reserve', MakeREservation , name='make-reservation-page'),          
    path('wishlist/', Wishlists , name='wishlist-page'),  
    path('wishlist/add/<int:product_id>', AddtoWishlist , name='add-to-wishlist-page'),  
    path('wishlist/remove/<int:item_id>', RemovefromWishlist , name='remove-from-wishlist-page'),  

    # End EP21

    
]

firstweb/pos/urls.py
from django.urls import path
# from .views import *
from . import views



urlpatterns = [
# path('',Sawatdee, name='home'),
path('tables/',views.AllTable, name='all-table'),
path('order/<int:table_id>/',views.OrderMenus, name='order-menu'),
path('monthly-order-summary/',views.MonthlyOrderSummary, name='monthly-order-summary'),
]

firstweb/myapp/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.contrib.auth.models import User

class Tracking(models.Model):
    name = models.CharField(max_length=100)
    tel = models.CharField(max_length=100)
    tracking = models.CharField(max_length=100,null=True,blank=True)
    other = models.TextField(null=True,blank=True)

    def __str__(self):
        return '{} - {} ({})'.format(self.name, self.tel, self.tracking)

class Product(models.Model):
    productId = models.IntegerField(default="0001")
    productName = models.CharField(max_length=100)
    categoryId = models.IntegerField()
    price = models.FloatField()
    detail = models.TextField(default="รายละเอียดสินค้า")

    def __str__(self):
        return '{} {} - {} ({}) - {}'.format(self.productId,self.productName, self.categoryId, self.price,self.detail)

class AskQA(models.Model):
    name = models.CharField(max_length=100, verbose_name='ชื่อ')
    email = models.CharField(max_length=100,null=True,blank=True,verbose_name='อีเมล')
    title = models.CharField(max_length=100,null=True,blank=True,verbose_name='หัวข้อ')
    detail = models.TextField(null=True,blank=True,verbose_name='รายละเอียด')
    answer = models.TextField(null=True,blank=True,verbose_name='ตอบคำถาม')

    def __str__(self):
        return '{} - {} ({}) - {}'.format(self.name, self.email, self.title, self.detail)


class Author(models.Model):
    author_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='author-image/', null=True,blank=True,default='default.png')

    def __str__(self):
        return self.author_name
    
class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=280,null=True,blank=True)
    body = models.TextField(null=True,blank=True)
    images = models.ImageField(upload_to="post_image",null=True,blank=True)
    date_created = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    date_updated = models.DateTimeField(auto_now=True,null=True,blank=True)
    slug = models.SlugField(unique=True,max_length=100, null=True,blank=True)
    tags = TaggableManager()

    def __str__(self):
        return self.title

class Category(models.Model):
    category_name = models.CharField(max_length=255, default="หมวดหมู่ทั่วไป")
    category_detail = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.category_name

class ProductName(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    introduction = models.TextField(null=True,blank=True)
    detail = models.TextField(null=True,blank=True)
    normal_price = models.IntegerField(null=True,blank=True)
    price1 = models.IntegerField(null=True,blank=True)
    price2 = models.IntegerField(null=True,blank=True)
    shipping_cost = models.IntegerField(null=True,blank=True,default=40)
    images = models.ImageField(upload_to="product", null=True, blank=True)
    quantity = models.IntegerField(default=1)
    available = models.BooleanField(default=True)
    unit = models.CharField(max_length=255,default="-")
    image_url = models.CharField(max_length=255,null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, max_length=100, null=True, blank=True)

    def __str__(self): 
        return self.name

class Order(models.Model):
    products = models.ForeignKey(ProductName, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    tel = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    address = models.TextField()
    count = models.IntegerField(default=1)
    buyer_price = models.FloatField(default=0)
    shipping_cost = models.FloatField(default=0)
    slip = models.ImageField(upload_to="prodcut-slip/")
    # เพิม field
    tracking_number = models.CharField(max_length=100, null=True, blank=True)
    not_complete = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name
# สร้าง Class Tracking Order
class TrackingOrderID(models.Model):
    tracking_order = models.ForeignKey(Order,on_delete=models.CASCADE, related_name="order_id")
    order_id = models.CharField(max_length=10)

    def __str__(self):
        return self.order_id



class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='profile_photo',null=True,blank=True)
    usertype = models.CharField(max_length=100,default='member')
    interestin = models.CharField(max_length=100,null=True,blank=True)
    facebook = models.CharField(max_length=100,default='No Facebook')
    address = models.TextField(null=True,blank=True)
    tel = models.CharField(max_length=100,null=True,blank=True)
    # EP17 
    cart_quantity = models.IntegerField(default=0, null=True, blank=True)
    # End EP17

    def __str__(self):
        return self.user.username

class OrderProduct(models.Model):
    order_id = models.CharField(max_length=100, null=True, blank=True)
    product_id = models.CharField(max_length=100, null=True,blank=True)
    product_name = models.CharField(max_length=100, null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    total = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.product_name
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_id = models.CharField(max_length=100, null=True, blank=True)
    product_name = models.CharField(max_length=100, null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    stamp = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    total = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.product_name
    
class CartOrder(models.Model):
    order_id = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    tel = models.CharField(max_length=14)
    email = models.CharField(max_length=50, null=True, blank=True)
    address = models.TextField()
    express = models.CharField(max_length=100)
    payment = models.CharField(max_length=100)
    other = models.TextField(null=True, blank=True)
    stamp = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    paid = models.BooleanField(default=False)
    confirm = models.BooleanField(default=False)
    slip = models.ImageField(upload_to="cart-slip/", null=True, blank=True)
    slip_time = models.DateField(null=True, blank=True)
    bank_account = models.CharField(
        max_length=50,
        choices= [
            ('KBank', 'KBank'),
            ('SCB', 'SCB'),
            ('TTB', 'TTB'),
            ('KTB', 'KTB'),
            ('BBL', 'BBL'),
            ('BAY', 'BAY'),
            ('อื่น', 'อื่น')
        ],
        default='KBank'
    )
    payment_id = models.CharField(max_length=100, null=True, blank=True)
    tracking_number = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.order_id



    
class Discount(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    percent = models.IntegerField(null=True,blank=True,default=10)
    active = models.BooleanField(default=False)


class Machine(models.Model):
    # list แบบข้อมูลข้างในคือ tuple
    MACHINE_TYPE = [
        ("cnd","CNC"),
        ("lathe", "เครื่องกลึง"),
        ("milling", "เครื่องกัด"),
        ("gear milling", "เครื่องไสเฟือง"),
        ]
    name = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    year = models.CharField(max_length=4)
    machine_type = models.CharField(max_length=100, choices=MACHINE_TYPE, default="CNC")
    images = models.ImageField(upload_to="machines", null=True, blank=True)
    price_per_day = models.IntegerField(default=0)
    price_discount = models.IntegerField(default=0, null=True, blank=True)
    earnest_money = models.IntegerField(default=1000, null=True, blank=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name
        # สางมากกว่า 1 ตัวทำแบบไหนก็ได้ มีผลเวลาที่เราสร้าง instand ขึ้นมา
        # เวลาจะเอาไปโชว์ โดยที่ไม่เลือกค่า มันจะโชว์ default เป็นตัวที่เรา return ไว้
        # เช่น for m in machines   ถ้าเรา {{m}} มันจะโชว์ name ตามที่เรา __str__ ไว้
        # แต่เราก็สามารถเรียกค่าอื่นๆได้โดย ใช่ {{m.name}} {{m.model}} อื่นๆ
        # return "{} - {}".format(self.name, self.model)
        # return f"{self.name} - {self.model}"
        # return self.name + " - " + self.model


class Reservation(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    id_card = models.CharField(max_length=13)
    customer_name = models.CharField(max_length=50)
    tel = models.CharField(max_length=11)
    email = models.CharField(max_length=50, null=True, blank=True)
    rental_price = models.IntegerField(default=0)
    total_rental_price = models.IntegerField(default=0)
    start_date = models.DateField()
    end_date = models.DateField()
    slip = models.ImageField(upload_to="machine-slip/", null=True, blank=True)

    def __str__(self):
        return self.customer_name

class Comments(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)   
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)

firstweb/myapp/templates/myapp/all-product.html
{% extends 'myapp/base.html' %}
{% block title %} เว็บแบงค์ - สินค้า {% endblock title %}
{% block content %}
  {% if user.is_authenticated and user.profile.usertype == 'vip' and user.discount.active == False %}
  <br><br>
  <div class="container">
    <div class="alert alert-primary" role="alert">
      คุณได้รับ <a href="{% url 'discount' %}" class="alert-link">ส่วนลดพิเศษ</a> ลด 10%
    </div>
  </div>
  {% endif %}


  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal text-body-white">สินค้าทั้งหมด</h1>
    <p class="fs-5 text-body-white">ร้านขายของแบงค์</p>
  </div>


      <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      {% for product in all_product %}
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
            {% if product.images %}
            <img src="{{ product.images.url }}" alt="" class="bd-placeholder-img card-img-top" width="100%" height="225px" style="object-fit: cover;">
            {% endif %}
            </div>
            <div class="card-body">
              <h5 class="card-title pricing-card-title">ราคา: {{ product.price1 }}<small class="text-muted fw-light"> THB</small></h5>
            {% if user.is_authenticated and user.profile.usertype in 'member,vip'  %}
              <a class="nav-link fw-bold py-1 px-0" href="{% url 'add-to-wishlist-page' product.id %}">
                <span class="badge bg-danger">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                    <path d="M8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                  </svg>
                </span>
              </a>
            {% endif %}
              <ul class="list-unstyled mt-3 mb-4">
                <li>{{ product.name }}</li>
                <li>หมวดหมู่: {{ product.category.category_name}} </li>
                <li>จำนวน: {{ product.quantity}}  <small class="text-muted fw-light"> {{ product.unit }}</small></li>
              </ul>
              <!-- EP17 -->
              <div class="text-end">
                {% if user.is_authenticated and user.profile.usertype in 'member,vip' %}
                <a href="{% url 'add-to-cart' product.id %}"><button type="button" class="btn btn-sm btn-outline-primary">เพิ่มไปยังรถเข็น</button></a>
                <a href="{% url 'product-detail' product.slug %}"><button type="button" class="btn btn-sm btn-primary">สั่งซื้อ</button></a>
                {% else %}
                <a href="{% url 'login' %}"><button type="button" class="btn btn-sm btn-danger">ไปที่หน้าล็อกอิน</button></a>
                {% endif %}
              <!-- End EP17 -->
              </div>
            </div>
          </div>
        </div>
      {% endfor %}

    
    </div>

{% endblock content %}

firstweb/myapp/templates/myapp/ask.html
{% extends 'myapp/base.html' %}
{% block title %} เว็บแบงค์ - สอบถามปัญหาทางนี้ได้เลย {% endblock title %}
{% block content %}

    {% comment %} ชื่อผู้ติดต่อ (text) {% endcomment %}
    {% comment %} email (text) {% endcomment %}
    {% comment %} หัวข้อ (text) {% endcomment %}
    {% comment %} รายละเอียด (textarea) {% endcomment %}

    <h2>สอบถามทางนี้ได้เลยครับ</h2><br>
    <div class="container text-start">
        <form action="" method="POST">
            {% csrf_token %}  {% comment %} เป็นคำสั่งเพื่อความปลอดภัย {% endcomment %}

            <div class="form-group">
                <label for="name">ชื่อผู้ติดต่อ</label>
                <input type="text" class="form-control" id="name" name="name" />
            </div>
            <br>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" id="email" name="email" />
            </div>
            <br>
            {% comment %}
            <div class="form-group">
                <label for="title">หัวข้อ</label>
                <input type="text" class="form-control" id="title" name="title" />
            </div>
            {% endcomment %}
            <div class="form-group">
                <label for="title">หัวข้อ</label>
                <select class="form-select" id="title" name="title">
                    <option>สินค้า</option>
                    <option>เคลมสินค้า</option>
                    <option>สอบถามข้อมูลสินค้า</option>
                    <option>อื่นๆ</option>
                </select>
            </div>
            <br>
            <div class="form-group">
                <label for="detail">รายละเอียด</label>
                <textarea class="form-control" name="detail" id="detail" rows="5"></textarea>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <br>

  

{% endblock content %}

firstweb/myapp/templates/myapp/contact.html
{% extends 'myapp/base.html' %}
{% block title %} เว็บแบงค์ - ติดต่อเรา {% endblock title %}
{% block content %}
  <h1>ติดต่อแบงค์</h1>
  <p class="lead">email: jittawatp@hotmail.com <br />tel: ส่ง email มาก่อนจะบอกเบอร์โทร</p>
{% endblock content %}

firstweb/myapp/templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% block title %} เว็บแบงค์ - หน้าแรก {% endblock title %}
{% block content %}
  <h1>เว็บสำหรับขายของ</h1>
  <p class="lead">อยากขายใครสนใจซื้อต่อไปใช้งานได้เลย</p>
  <p class="lead">
    <a href="#" class="btn btn-lg btn-light fw-bold border-white bg-white">ไปดูกันเลย</a>
  </p>
{% endblock content %}

firstweb/myapp/templates/myapp/machine-detail.html
{% extends 'myapp/base.html' %}
{% load static %} 
{% load humanize %} <!-- การใส่ comma ใน html line -->
{% block title %} เว็บแบงค์ขายสินค้า - รายละเอียดสินค้า {% endblock title %}
{% block content %}
<main class="container">
    <div class="row g-4  text-start">
  <div class="col-md-8">
  <article class="blog-post">
    <p class="display-5 link-body-emphasis mb-1 text-white">{{machine.name}} {{machine.model}}</p>
    <hr>
    {% if machine.images %}
    <img src="{{ machine.images.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
    {% else %}
    <p>ไม่มีรูปภาพ</p>
    {% endif %}
  
    <div style="padding-top: 20px"></div>
    <blockquote class="blockquote">
      <p> {{ machine.year }}</p>
    </blockquote>
    <p> {{ machine.get_machine_type_display }}</p>
    <div style="padding-top: 20px"></div>
    <p>ราคา {{ machine.price_per_day }} ต่อวัน</p>
    <div style="padding-top: 20px"></div>
    <div class="row text-left">
    <a href="{% url 'make-reservation-page' machine.id %}" class="btn btn-primary btn-sm">ไปที่รายการเช่า</a>
    </div>
    <div style="padding-top: 100px"></div> 
    
      <!-- comments -->
    {% for comment in comments %}
    <div class="user-comment mb-6">
    

      <div class="author flex items-center mb-4">
        <div class="profile-pic mr-4">
          <img class="w-12 h-12 rounded-full" src="{% static 'images/00.png'  %}" width="60" alt="" />
        </div>
        <div class="details">
          <p class="font-semibold text-lg">{{ comment.name }}</p>
          <small class="text-white-500">{{ comment.date | date }}</small>
        </div>
      </div>
      <div class="comment-sec-main bg-white-100 p-4 rounded-lg">
        <div class="comment-sec mb-4">
          <div class="comment mb-4">
            <p class="text-white-700">{{ comment.content }}</p>
          </div>
          <div class="reply text-right">
            <button class="text-blue-500 hover:text-blue-700" onclick="toggleDiv(this)">ตอบความคิดเห็น</button>
          </div>
          <div class="comment-box hidden mt-4" style="display: none;" id="comment-reply-box">
            <h3 class="text-lg font-semibold mb-2">ตอบกระทู้</h3>
            <p class="text-sm text-white-600 mb-4">
              ที่อยู่อีเมลของคุณจะไม่ถูกเผยแพร่
              <span class="text-red-500">*</span>
            </p>
            <form method="POST" class="space-y-4">
              {% csrf_token %}
              <!-- <input type="hidden" name="" value=""> -->
              <input type="hidden" name="parent" value="{{ comment.id }}">
              <textarea name="content" class="w-full p-2 border rounded-md" rows="4" required></textarea>
              <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                <input type="text" name="name" class="p-2 border rounded-md" placeholder="ชื่อของคุณ" required>
                <input type="email" name="email" class="p-2 border rounded-md" placeholder="อีเมล์ของคุณ" required>
                <input type="text" name="website" class="p-2 border rounded-md" placeholder="เว็บไซต์ของคุณ" required>
              </div>
              <button class="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600">
                Post Reply
              </button>
            </form>
          </div>  
        </div>
   {% for reply in comment.replies.all %}
   <div class="public-reply pl-8 border-l-2 border-gray-200 mt-4 text-right">
          <div class="author flex items-center flex-row-reverse mb-2">
            <div class="profile-pic ml-4">
              <img class="w-10 h-10 rounded-full" src="{% static 'images/00.png'  %}" width="40" alt="" />
            </div>
            <div class="details text-right">
              <p class="font-semibold text-md">{{ reply.name }}</p>
              <small class="text-gray-500">{{ reply.date | date }}</small>
            </div>
          </div>
          <div class="comment">
            <p class="text-white-700">{{ reply.content }}</p>
          </div>
        </div>
    {% endfor %}
      </div>
    </div>
    {% endfor%}
    <!-- comments end -->
  
    <!-- Leave a new comment -->
    <div class="comment-box mt-8">
      <h3 class="text-xl font-semibold mb-4">ฝากความคิดเห็นใหม่กับโพสต์นี้</h3>
      <p class="text-sm text-white-600 mb-4">
        ที่อยู่อีเมลของคุณจะไม่ถูกเผยแพร่
        <span class="text-red-500">*</span>
      </p>
      <form method="POST" class="space-y-4">
        {% csrf_token %}
        <!-- <input type="hidden" name="" value=""> -->
        <textarea name="content" class="w-full p-2 border rounded-md" rows="4" required></textarea>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <input type="text" name="name" class="p-2 border rounded-md" placeholder="ชื่อของคุณ" required>
          <input type="email" name="email" class="p-2 border rounded-md" placeholder="อีเมล์ของคุณ" required>
          <input type="text" name="website" class="p-2 border rounded-md" placeholder="เว็บไซต์ของคุณ" required>
        </div>
        <button class="btn btn-primary btn-sm">
          โพสต์ความคิดเห็น
        </button>
      </form>
    </div>
  <script>
        function toggleDiv(a) {
            const replaybox = a.parentNode.parentNode.parentNode.querySelector(".comment-box");
            if (replaybox.style.display === "none"){
                replaybox.style.display = "block";
            } else {
                replaybox.style.display = "none";
            }
        }
  </script>
  <!-- comments end -->
  </article>
  </div>
  <div class="col-md-4">
  <div class="position-sticky" style="top: 2rem;">
    <div>
      <h4 class="fst-italic">เครื่องใหม่ล่าสุด</h4>
      <ul class="list-unstyled">
        <li>
        {% for machine in machines %}
          <a href="{% url 'machine-detail-page' machine.id  %}" class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top">
            {% if machine.images %}
            <img src="{{machine.images.url}}" alt="" style="width: 30%; height: 100%; object-fit: cover;">
            {% else %}
            <p>ไม่มีรูปภาพ</p>
            {% endif %}
            <div class="col-lg-8">
              <h6 class="mb-0" style="color:white">{{ machine.name }}</h6>
            </div>
          </a>
        {% endfor %}
        </li>
      </ul>
    </div>
  <!-- 
    <div class="p-4">
      <h4 class="fst-italic">ช่องทางติดตาม</h4>
      <ol class="list-unstyled">
        <li><a href="https://www.facebook.com/UncleEngineer/" target="_blank">Facebook</a></li>
        <li><a href="https://www.youtube.com/@UncleEngineer" target="_blank">YouTube</a></li>
        <li><a href="https://uncle-engineer.com/" target="_blank">Website</a></li>
      </ol>
    </div> -->
  </div>
  </div>
    </div>
  </main>
  
{% endblock content %}